### ISSUE TITLE
[Feature Request] Colours for list hyphens/stars and headers

### ISSUE THREAD

**Issue by Justinzobel** [agateau/nanonote#43] opened 2023-03-12 23:51 UTC
It would be great to have the option to do colours for list hyphen/stars so they stand out slightly.

I'd also love to see headers that start with a # or something similar. No change in font size, just colour to have them stand out.

Keep up the good work. Because of the internal dependencies of this I might try making a flatpak.

**Comment by dlaidig** [comment] 2023-03-22 17:57
While I don't have any strong opinions, I had some thoughts while reading this, so I'll just dump them here in case they turn out to be useful:

- For the list items: Nanonote actually does auto-completion for lists, so one might argue that it is useful to get some visual feedback that this syntax has been recognized.
- Even without that, I would guess that the "highlighting can help to recognize the structure" argument can in theory apply equally to list items and headings.
- Not sure if highlighted list items generally would improve things for me or mostly add visual clutter. I guess that would also heavily depend on the chosen style. One situation in which I found lists really hard to recognize is when the items are long and word-wrapped.
- For the headings: When selecting a suitable style, keep in mind that `#` might also indicate a source code comment. (Not an issue to highlight those, but the style should probably not signal emphasis.)

**Comment by agateau** [comment] 2023-03-23 21:36
For information, I experimented with just making lines starting with `#` bold, and I like it:

![image](https://user-images.githubusercontent.com/3575/227369105-50834df2-751f-49eb-b9c2-2bd9ea988a34.png)

You can try it from the `highlight-heading` branch.

**Comment by dlaidig** [comment] 2023-03-24 08:55
I also like it. :)

One thing I noticed is that on Breeze Dark (and probably on all dark themes), the bold font stands out a lot less than on light themes. But I guess that is just how it is. Probably still better than using colors.

I also quickly played around with some source code and while I found it a bit irritating sometimes, I don't think it's a big issue. It will anyway only affect top-level comments, and in the worst case, one can always temporarily indent the whole code block.

Btw, is it on purpose that the CI did not run for this branch? I guess it's probably caused by the change in 5ac52821ee7af1b51d269df1a0155f2c771764a4.

**Comment by agateau** [comment] 2023-04-02 20:59
> I also quickly played around with some source code and while I found it a bit irritating sometimes, I don't think it's a big issue. It will anyway only affect top-level comments, and in the worst case, one can always temporarily indent the whole code block.

Just pushed the changes and published 1.3.92 which contain them!

> Btw, is it on purpose that the CI did not run for this branch? I guess it's probably caused by the change in https://github.com/agateau/nanonote/commit/5ac52821ee7af1b51d269df1a0155f2c771764a4.

Yes, this is to avoid an annoying issue with GitHub CI: if the CI is configured to build on all pushes and on all PRs, then when one opens a PR, all builds happen twice: once for the push and once for the PR.

**Comment by agateau** [comment] 2023-04-02 21:00
I am going to close this now that 1.3.92 is out.

**Closed by agateau** 2023-04-02 21:00 UTC
